[build]
command = "rm -rf node_modules && pnpm install && pnpm build"
publish = ".next"
functions = "netlify/functions"

[build.environment]
CI = "true"
PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
PRISMA_CLIENT_ENGINE_TYPE = "binary"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "prisma"]

[[plugins]]
package = "@netlify/plugin-nextjs"
