[build]
command = "pnpm install && pnpm prisma:full-setup && pnpm build"
publish = ".next"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "23"
PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
PRISMA_CLIENT_ENGINE_TYPE = "binary"
PRISMA_GENERATE_ONLY = "true"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "prisma"]

[[plugins]]
package = "@netlify/plugin-nextjs"
